apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitlement-key
  namespace: cp4i-apic
spec:
  encryptedData:
    .dockerconfigjson: AgBPRbmmhxStTDWyNPzKbfZkceLAVeWcg5c8Mnl6EK5MOjKKm/sVp/LycQrMPqtNGwXFNHkw50AgZrXk9MmL2ezW+IHMzSY0dmIfqOW3RFjTWd+g74QzMvgH6+1i4uufilKQZ3WHgvpGiM7xuSyqBvQdJOOTa5rPlqEu0Sv62j7/KOqF5fCnHn0J8RWLl5yHcfivqcOKu5ndp7EqTIEFs0vFrnsAsVWFSedFHTT+Z52dFh2LAGNMVHvpGQPfrIT414lM1nFhxV/VH9W/UlYW625MsfF8AnkTMji41XNqCjCLT5n9yzM9H6YTSIpT72k3GIbXiU82w8fRGfrEvTxwajIcc5Y2zW6Ifq6gfs58Xs9oM2AQUM0KwHdmuJQ6oMKwE4dDCQ7fk/uJkR4IDEts9r8aHbbYzQiXqnTkuj+q9u/WsKIvwSkj4UZQbBGmqHw9UTmqJHgTGsE8+Q0Zr2MSyfebh1QD4K/MWGG9T8cfNF/xivZ963Dfpp0Y32fQ7ojKuIDg6UmloI25FIAhlrVr1sA/RF7R72PhU8KEPvK9zlY2B6gzbzUKh2/9ncn1ek6NSdTZ89vSm6KHDqkrhJZYzm99RdmBG7W3PUmOKWayQVCD7egoodUZt9XeH8GnOqQq9P3AryOZNVi8qvzxH5zhIsoFfjkGeEDoaYpBP5d52JaMgsQIuGRKhiQ3IvaxffrJUr+Sipz7J5GOSE9ndT3r5eioWJ9GSVhNjspkb8uf+MKsmpPOhQ3psYLcMOBssp/C5tIzSZQ1ocC8M3xP6w1ghezhENFit9VsH84ytPoHTB/lrL9f8UREg6Fihwh8xEeZe6FpWXi5ae0Bn0OjKPUV/4pOhed9l6KekDsO1Wl/o5oq0x5dXqlTCEd01icyApy8Cl/MjDUPARDaPEh2e5ORF7BpvdC6QQeAPT6EOl54PBueGO3t5ZFJMr/sCgZx8Rkg3cb+aIfKBtD7QHOmzLuXKpOWbQ2vcbYzGvgo1dXwnV2TMkdB2gbedZ5SzWK8yY14KRt5o9X39KvlsHtW3MWIiVMRb6YprlRVFhvNdtxKSPcGL6KJ+9mTmokBZXCVsckGgSBPvh3IsKTAicjfr7nXb1lrm29/Th9r3l+vyFJysXqCvK6TlYnf4MTymF3l31qDVG1mW/bGu9jmZsJbMRbxMQvPLx5g5sUv1jmvHSZL+cvAjF4g9wClXddGUfRs4Y4rHIoZj/X7fNHPZqRb2Fq1Vbu39971fvNVap9DPdch4sk/R33syb5jzh5wPhLauX2P36pNPxHUGMBRP9Jezq1hhDDG2RoxKKB+4wK81jyyS77iscV4N9ySwLJs3J97zGW9p9un
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitlement-key
      namespace: cp4i-apic
    type: kubernetes.io/dockerconfigjson

